<a href="https://colab.research.google.com/github/altamashalk/py/blob/master/numpy_introduction2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NumPy Attributes

In [ ]:
import numpy as np

In [ ]:
x1=np.random.randint(20,size=5) #one dimensional array
print(x1)

[ 6 11  5 17  9]


In [ ]:
x2=np.random.randint(10,size=(3,4)) #Two dimensional array
print(x2)

[[9 7 5 0]
 [0 3 4 7]
 [9 8 3 8]]


In [ ]:
x3=np.random.randint(10,size=(3,4,5)) #Three dimensional array
print(x3)

[[[4 0 4 3 6]
  [3 1 9 2 2]
  [0 3 5 1 8]
  [5 3 0 4 1]]

 [[1 7 4 5 2]
  [7 4 3 2 6]
  [8 7 5 7 3]
  [2 8 0 7 9]]

 [[6 9 2 4 0]
  [5 6 6 1 8]
  [9 4 0 6 1]
  [9 5 9 8 4]]]


In [ ]:
print("x1 ndimension: ", x1.ndim)
print("x1 shape: ",x1.shape)
print("x1 size: ",x1.size)
print("x1 Data Type: ", x1.dtype)
print("x1 size of element",x1.itemsize,'bytes')
print("x1 size of array",x1.nbytes,"bytes")

x1 ndimension:  1
x1 shape:  (5,)
x1 size:  5
x1 Data Type:  int64
x1 size of element 8 bytes
x1 size of array 40 bytes


In [ ]:
print("x2 ndimension: ", x2.ndim)
print("x2 shape: ",x2.shape)
print("x2 size: ",x2.size)
print("x2 Data Type: ", x2.dtype)
print("x2 size in bytes",x2.itemsize)
print("x2 size of array",x2.nbytes,"bytes")

x2 ndimension:  2
x2 shape:  (3, 4)
x2 size:  12
x2 Data Type:  int64
x2 size in bytes 8
x2 size of array 96 bytes


In [ ]:
print("x3 ndimension: ", x3.ndim)
print("x3 shape: ",x3.shape)
print("x3 size: ",x3.size)
print("x3 Data Type: ", x3.dtype)
print("x3 size in bytes",x3.itemsize)
print("x3 size of array",x3.nbytes,"bytes")

x3 ndimension:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 Data Type:  int64
x3 size in bytes 8
x3 size of array 480 bytes


# 2. Array Indexing

In [ ]:
x1[0]

np.int64(6)

In [ ]:
x1[2]

np.int64(5)

In [ ]:
x1[-1]

np.int64(9)

In [ ]:
x1[-3]

np.int64(5)

In [ ]:
for var1 in range(5):
  print(x1[var1])
  #method used as in other languages

6
11
5
17
9


In [ ]:
x2

array([[9, 7, 5, 0],
       [0, 3, 4, 7],
       [9, 8, 3, 8]])

In [ ]:
x2[0,0]
#x2

np.int64(9)

In [ ]:
x2[0,1]#first(zero)row and second column

np.int64(7)

In [ ]:
print(x2)
x2[2,-1]# Third row and last element

[[9 7 5 0]
 [0 3 4 7]
 [9 8 3 8]]


np.int64(8)

In [ ]:
x2

array([[9, 7, 5, 0],
       [0, 3, 4, 7],
       [9, 8, 3, 8]])

In [ ]:
x1[2]=7.4
x1

array([ 6, 11,  7, 17,  9])

# 3. Array Slicing

In [ ]:
x4=np.arange(20)
print(x4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


*variable_name[start: stop:step]*

In [ ]:
x4[:5]#slice first five elements i.e stop at 5th element

array([0, 1, 2, 3, 4])

In [ ]:
x4[5:] # start after 5th element

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
x4[3:6]

array([3, 4, 5])

In [ ]:
x4[0::2]#every other element

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
x4[3:15:2]

array([ 3,  5,  7,  9, 11, 13])

In [ ]:
x4[-1::]

array([19])

In [ ]:
x4[-1::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [ ]:
x4[7::-1]


array([7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x4[7:3:-1]


array([7, 6, 5, 4])

In [ ]:
x2

array([[9, 7, 5, 0],
       [0, 3, 4, 7],
       [9, 8, 3, 8]])

In [ ]:
x2[0:2,:3]#two rows and three columns

array([[9, 7, 5],
       [0, 3, 4]])

In [ ]:
x2[0:3,::2]

array([[9, 5],
       [0, 4],
       [9, 3]])

In [ ]:
x2[:,0]#first column

array([9, 0, 9])

In [ ]:
x2[0,:]#First row

array([9, 7, 5, 0])

In [ ]:
x2

array([[9, 7, 5, 0],
       [0, 3, 4, 7],
       [9, 8, 3, 8]])

In [ ]:
x2_sub_a=x2[:1,:2]#one row and two column are sliced and stored in another variable
print(x2_sub_a)

[[9 7]]


In [ ]:
x2_sub_a[0,0]=15
print(x2_sub_a)

[[15  7]]


In [ ]:
x2

array([[15,  7,  5,  0],
       [ 0,  3,  4,  7],
       [ 9,  8,  3,  8]])

In [ ]:
x2_sub_a_copy=x2[:1,:2].copy()#for copying the slice
print(x2_sub_a_copy)

[[15  7]]


In [ ]:
x2_sub_a_copy[0,0]=25
print(x2_sub_a_copy)

[[25  7]]


In [ ]:
x2

array([[15,  7,  5,  0],
       [ 0,  3,  4,  7],
       [ 9,  8,  3,  8]])

# 4. Reshaping of Arrays

In [ ]:
x5=np.arange(0,15)
print(x5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
x5.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x6=np.arange(0,6).reshape((2,3))
print(x6)

[[0 1 2]
 [3 4 5]]


In [ ]:
x6.reshape((6,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
x7=np.arange(5)
print(x7)
x7[:, np.newaxis]
#x7[np.newaxis,:]


[0 1 2 3 4]


array([[0],
       [1],
       [2],
       [3],
       [4]])

# 5. Joining and Splitting of Arrays

In [ ]:
array1=np.array([1,2,3])
array2=np.arange(5,10,2)
print(array1)
print(array2)
np.concatenate([array1,array2])

[1 2 3]
[5 7 9]


array([1, 2, 3, 5, 7, 9])

In [ ]:
array3=np.arange(1,10).reshape((3,3))
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.vstack([array1,array3])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array4=np.array([[5],[6],[7]])
np.hstack([array3,array4])

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 7]])

Splitting of Arrays

In [ ]:
array_s1=np.arange(0,15,1)
print(array_s1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
arr1,arr2,arr3 =np.split(array_s1,3)
print(arr1,arr2,arr3)

[0 1 2 3 4] [5 6 7 8 9] [10 11 12 13 14]


In [ ]:
array_s01=np.arange(0,17,1)
print(array_s01)
a1,a2,a3,a4 = np.split(array_s01,[5,7,10])
print(a1,a2,a3,a4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[0 1 2 3 4] [5 6] [7 8 9] [10 11 12 13 14 15 16]


In [ ]:
grid = np.arange(16).reshape((4, 4))
print(grid)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
